### ISSUE TITLE
Code Critique Vol. 1

### ISSUE THREAD

**Issue by gek169** [rizet/skylight#2]
I had a lot of fun reading your code and I want to thank you for it. It was very enjoyable and educational.

1) Undefined behavior. Obsessive use of double underscore names is the least of it, implicit pointer integer conversions and mixed signed/unsigned... I shudder to think about it. Maybe you copy-pasted it from somewhere, or OSdevers told you it was a good idea?

2) Extremely bad symbol names. you export a variable called "initialized". Need I say any more?

![Screenshot from 2021-05-22 00-28-39](https://user-images.githubusercontent.com/6974902/119214788-74f56780-ba97-11eb-9ee4-00a60e14d3a7.png)

3) Bugs. There are two at work here, one is obvious (test case: any negative number), the other is evil:
![Screenshot from 2021-05-22 00-31-58](https://user-images.githubusercontent.com/6974902/119214809-99514400-ba97-11eb-925d-848d3b360783.png)

(I believe there's actually a third bug in the itoa function that I figured out while looking at your other code, but I'm not confident in it.)

Oh, the fun you'll have debugging this one if it ever shows itself. You probably won't. Please don't put this in production code, I almost missed it myself. (EDIT: This one is actually a multi-headed beast. The other heads are less fearsome but far cleverer)
![Screenshot from 2021-05-22 00-33-59](https://user-images.githubusercontent.com/6974902/119214821-ac641400-ba97-11eb-853c-aed0cb92faf0.png)

4) Coding conventions that look like obfuscation techniques

I suspect you copy-pasted this from somewhere. Also, there's at least 2 bugs. They're very trivial and you'll find them immediately.

EDIT: there is a secret evil bug that isn't showing itself due to the set of compiletime constants you chose. I thought this one was trivial but no, it's got some evil.

![Screenshot from 2021-05-22 00-30-14](https://user-images.githubusercontent.com/6974902/119215056-3eb8e780-ba99-11eb-8d7b-570cf45055e6.png)

I mentioned this function before. I'd call it exceptionally bad to have a pre-declaration outside of your headers. The function prototype being alone like this should help you figure out the other bug (No, not the negative number one).

![Screenshot from 2021-05-22 01-06-32](https://user-images.githubusercontent.com/6974902/119215189-0fef4100-ba9a-11eb-80a6-40799412f714.png)

**Comment by rizet** [comment]
Thanks for your input.

As for the "obsessive" use of double underscore names, I would just like to put in that double underscore names, according to convention, belong to symbols that are defined by the compiler or the C library. My implementations of a few string functions do indeed count as "defined by the C library".

As for the bad symbol names, i.e. "initialized". I could have named it better. I assumed it would be understandable considering the context it was in. In hindsight, if I ever wished to do something of the same for some other kernel function, I would have a rather hard time resolving linker symbol redefinitions.

As for `itoa` bugs: I am *completely* aware of them. I do not have the proper facilities implemented in my kernel yet in order to make a proper `itoa`. The negative number bug is unresolved because I plan to scrap my current `itoa` implementation entirely. As for the other "evil" you didn't describe: I am aware that my `itoa` would be rather problematic if there was an attempt to call it with a `base` > 16. Like I said: crappy `itoa`, will rewrite later.

As for the `strlen` bug: that `strlen` was taken almost word for word from musl's implementation. I am aware of how it works but I am unaware of what this possible "bug" could be.

As for the `gdt_install_tss` bug, no, it's not copy-pasted. Also, I am unaware of what this possible "bug" could be. 

As for the declaration of `itoa` outside of a header: I didn't want to write a header for a single function, and `itoa` was not declared in any of my standard headers (provided by clang 10).

If you would elaborate on some of these bugs: that would be appreciated.

**Comment by gek169** [comment]
itoa not working for bases above 16 is not the bug i was talking about. I actually didn't think to call that a bug, I assumed you were just calling it a requirement of the function. Have you ever heard of "Sign Extension" ? 

Many of your bugs come from implicit signed-unsigned conversions and they're doing them between types of different sizes. Question: What happens when you convert negative one from a 32 bit "int" to a 64 bit "long unsigned int" (As it is in GCC?) No, it's not 4 billion. You should try running a simple test. enter negative one as the first argument to this program:
```c
#include <stdlib.h>
#include <stdio.h>
int main(int argc, char**argv){
	volatile int a;
	volatile long unsigned int b;
	a = atoi(argv[1]);
	b = a;
	printf("\n%lu\n", b);
}
```

that should help you determine several of these bugs.

Pointer subtraction returns a signed ptrdiff_t. This type is implementation defined and is thus unreliable. If it is 'int' then your implementation is bugged for strings longer than 2 Gigabytes... which may sound unusual but wait until someone opens a big text file.

Read: https://en.cppreference.com/w/cpp/types/ptrdiff_t
http://port70.net/~nsz/c/c89/c89-draft.html#3.3.6

the gdt functions have integer bugs in the same class and I think given the hints you should be able to figure them out.

If what you say is true about that strlen implementation being in musl, you should send a bug report mentioning the fact it either A) relies on non-standard behavior for an edge case or B) doesn't work correctly. In general, I'd say *never* rely on pointer subtraction, it's just bad practice.

The third bug that i'm not sure if it's a bug or not is the fact that you made a static array... and there are 3 unused characters. 60, plus You're using one for the null terminator, and then... the other three are for... padding alignment?

**Comment by rizet** [comment]
I have noticed the TSS-type-field size mismatch, resolving soon.

**Comment by rizet** [comment]
Resolved all `itoa` bugs with `d941eb2`.

**Comment by rizet** [comment]
Resolved all `strlen` UB with 8ad235e.

**Comment by rizet** [comment]
Resolved all bad symbol exports with 36b00dd.

**Comment by rizet** [comment]
Resolved most if not all undefined conversions with acf11bc.

**Comment by rizet** [comment]
Resolved all topics in the issue. Commits involved:
 - 420e066
 - d941eb2
 - 8ad235e
 - 36b00dd
 - acf11bc
 
If you still notice some undefined behavior, feel free to open a new issue. Closing this issue now.
